### ISSUE TITLE
A-DC-Coerce detection differences

### ISSUE THREAD

**Issue by mavhc** [netwrix/pingcastle#242]
Running 3.2.0.1 detects A-DC-Coerce flaw
Running 3.3.0.0 beta does not detect it

I have: "
Network security: Restrict NTLM: Outgoing NTLM traffic to remote servers" set to "Audit all"

**Comment by vletoux** [comment]
last beta remove the results if this is coming from the local machine.
I bet you ran PingCastle from a DC

**Comment by JoeDibley** [comment]
Closing this issue as no reply and a potential solution offered. Please reopen if this is still an issue in the newly released version.
