### ISSUE TITLE
P-RODCAdminRevealed doesnt seem to be accurate.

### ISSUE THREAD

**Issue by michaeldjones1980** [netwrix/pingcastle#248]
No matter if I look at the RODC computer object attributes section, or if I use powershell to show revleaed users I am not able to see any of the users listed in the section of the report.  This is happening for all of my RODC and I am not sure why adding 190 points to my score.  

Not sure how this data is pulled but I am pretty sure it's wrong.   How is the data pulled. Maybe I can replicate results and that will help me figure out how to resolve.  

![image](https://github.com/user-attachments/assets/73cf421c-1312-4de0-b0c1-d8b5d67e5fe8)

**Comment by JoeDibley** [comment]
Thanks for the detailed question and response here. It should be noted that if discovered and privileged account passwords are reset etc you can use tools like repadmin to remove accounts from these fields.

RepAdmin /prp delete documentation: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc835090(v=ws.11)#delete

Please reopen if more help is required.
