### ISSUE TITLE
S-PwdLastSet-45: Detects accounts that has changed passwords 14 days ago

### ISSUE THREAD

**Issue by PorreKaj** [netwrix/pingcastle#251]
Seems like there is a bug in riskrule S-PwdLastSet-45, where it falsely reports issues with computers that has had password chance as recently as 2 weeks ago.

![image](https://github.com/user-attachments/assets/4459ddef-1262-47ac-ae2b-580ebddf7bc7)

I'd wager that there might be a bug in the handling of dates since we just entered September.

**Comment by An-dir** [comment]
You should check the LastLogonDate as well. Sometimes LastLogonDate is far in the future. 

(PwdLastSet +45 days) < LastLogonDate 
Take a look at the source to understand it: https://github.com/netwrix/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledPwdLastSet45.cs#L26

**Comment by PorreKaj** [comment]
Sure, but thats not really relevant for the Password last set attribute :-)

**Comment by An-dir** [comment]
Why

Rene Hansen ***@***.***> schrieb am Do., 5. Sept. 2024, 07:12:

**Comment by An-dir** [comment]
a computer should normally change it's password every 30 days. It can only do this when it was connected to the AD. so the online state is represented by lastlogontimestamp.

**Comment by PorreKaj** [comment]
oh sorry sure, I meant for the rule check, last logon shouldn't be relevant.
all servers related to the screenshot of dates are in use, and the last logon attributes are recent.

**Comment by An-dir** [comment]
ok. did you try running pingcastle with an administrator elevated. in some configurations pingcastle cannot detect all data and the calculation cannot be accurate.

**Comment by PorreKaj** [comment]
Last logon might be relevant after all, for some reason they are all in the future for those devices.
I assume Pingcastle evaluates the age of the password by comparing lastlogon with password last set.
