### ISSUE TITLE
S-PwdNeverExpires not consistently included in reports

### ISSUE THREAD

**Issue by PorreKaj** [netwrix/pingcastle#257]
I noticed since 3.3.0.0, that S-PwdNeverExpires is no longer included in the reports from domains that has a massive amounts of those accounts.

The changelog mention changes to this, and other rules, and also mentions the hard limit for displaying 100 accounts for non-pro accounts.
Could there be a bug where the rules simply is ignored altogether if there a more than 100 accounts?
The reports from domains where the rule hits less than 100, includes the rule just fine. but in another domain with 6000 accounts with PC never expires, the rule is not in the report.

**Comment by vletoux** [comment]
This is design to allow a limited set of exceptions but do not produce a gigantic html report is you have 10 000 accounts.
Previously nothing was displayed here and I remember that in the main report you have also a limit (maxitemindisplay)

**Comment by PorreKaj** [comment]
Thanks for the swift reponse.
I understand the part about not having detailed information, the issue I'm trying to convey, is that the riskrule is entirely missing from the new reports.

Left side here is 3.2.0.1, right side is 3.3.0.0
![image](https://github.com/user-attachments/assets/15359626-36be-4030-b9e2-16cab312bb4a)

**Comment by JoeDibley** [comment]
Yep. Confirmed internally too. We will let you know when this is resolved and a new update released.

**Comment by JoeDibley** [comment]
This should all be resolved in the latest version, version 3.3.0.1. Please reopen the issue if this is still a problem for you. Thanks again.
