### ISSUE TITLE
How to add an exception?

### ISSUE THREAD

**Issue by KAPMAH1986** [netwrix/pingcastle#258]
Good day.

Can you tell me how to exclude a check from the report?
LAPS adds 15 points to me, but I use other tools. In the solution, it says that this item can be excluded from the check. But how? There are no exceptions in the help or in the config file.

Here is this item:

Advised solution:
If you don't have any provisioning process or password solution to manage local administrators, you should install the LAPS solution. If you mitigate the risk differently, you should add this rule as an exception, as the risk is covered.

Thanks in advance!

**Comment by JoeDibley** [comment]
Hi there,
Implementing exceptions is a feature that is used in the Web Application for PingCastle, the Pro and Enterprise versions. Without this you would need to change the XML to fake the data or similar and regenerate the reports.

I will add an item to the backlog to amend this wording to avoid confusion in the future.

**Comment by KAPMAH1986** [comment]
Got it, thankss
