### ISSUE TITLE
 Could not load file or assembly 'System.Net.Http, Version=4.2.0.0,

### ISSUE THREAD

**Issue by dest50** [netwrix/pingcastle#259]
hello,
when i try to run pingcastle on domain controllei got these error meesage ? 
Can you help me 
<img width="484" alt="Capture d’écran 2024-09-19 104757" src="https://github.com/user-attachments/assets/21ff664f-f7db-4cb7-b298-095ba29812aa">
Regards ,

**Comment by JoeDibley** [comment]
Hi there, 
this is a .NET Framework error. You should be able to install .NET Framework and be good to go. 
Please be aware that PingCastle works best when run from a Server/Workstation, not a domain controller as it cannot confirm certain findings locally such as Domain Controller Coercion.

**Comment by JoeDibley** [comment]
Closing issue as no reply. Please reopen if this is still an issue for you.
