### ISSUE TITLE
PingCastle execution causing "unsecure LDAP binding" audit event

### ISSUE THREAD

**Issue by red-erik** [netwrix/pingcastle#264]
Hello,
when we run PingCastle, we immediately recive a waring for an unsecure LDAP binding
due to our monitoring on LDAP Packet Signing Enforcement setting.
Do you think it would be possicle to change that ?

The following client performed a SASL (Negotiate/Kerberos/NTLM/Digest) LDAP bind without requesting signing (integrity verification), or performed a simple bind over a clear text (non-SSL/TLS-encrypted)LDAP connection.

Regards,
Red.

**Comment by JoeDibley** [comment]
Hi there,
I don't think we can change this im afraid as it is part of the healthcheck. The A-DCLdapSign rule performs an actual check to detect whether it is actually enforced or not.

You can see more about the rule by searching A-DCLdapSign in the PingCastle rules located [here](https://pingcastle.com/PingCastleFiles/ad_hc_rules_list.html).

**Comment by red-erik** [comment]
Hello,
thanks for the clarification.

Regards,
Red.
